"""add_timestamps

Revision ID: 32e1e9f57ccf
Revises: 8ef9378fe549
Create Date: 2026-05-28 20:17:42.964462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e1e9f57ccf'
down_revision: Union[str, None] = '8ef9378fe549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('empty_weighted_at', sa.DateTime(), nullable=True))
    op.add_column('purchases', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'completed_at')
    op.drop_column('purchases', 'empty_weighted_at')
    # ### end Alembic commands ###
