"""remove_car_number_jin_weight_add_farmer_weights

Revision ID: 9b065a49a127
Revises: 32e1e9f57ccf
Create Date: 2026-05-28 20:25:12.478944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b065a49a127'
down_revision: Union[str, None] = '32e1e9f57ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('total_gross_weight', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('farmers', sa.Column('total_empty_weight', sa.Numeric(precision=14, scale=2), nullable=True))
    op.drop_column('farmers', 'car_number')
    op.drop_column('purchases', 'jin_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('jin_weight', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('farmers', sa.Column('car_number', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('farmers', 'total_empty_weight')
    op.drop_column('farmers', 'total_gross_weight')
    # ### end Alembic commands ###
