"""add_server_default_farmer_weights

Revision ID: a2093f6d4eac
Revises: 9b065a49a127
Create Date: 2026-05-28 20:27:17.115165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2093f6d4eac'
down_revision: Union[str, None] = '9b065a49a127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
